# SwiftLint <https://realm.github.io/SwiftLint/>
#
check_for_updates: false

disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - nesting
  - todo
  - trailing_comma
  - trailing_newline
  - type_body_length

  # TODO
  - comma
  - comment_spacing
  - control_statement
  - deployment_target
  - empty_enum_arguments
  - empty_parentheses_with_trailing_closure
  - for_where
  - force_cast
  - implicit_getter
  - implicit_optional_initialization
  - legacy_constant
  - legacy_constructor
  - line_length
  - mark
  - multiple_closures_with_trailing_closure
  - no_fallthrough_only
  - opening_brace
  - orphaned_doc_comment
  - private_over_fileprivate
  - shorthand_operator
  - switch_case_alignment
  - syntactic_sugar
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_synthesized_initializer
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - vertical_parameter_alignment
  - vertical_whitespace

identifier_name:
  min_length: 1
  allowed_symbols: ["_"]
  excluded:
    - Core.*

type_name:
  min_length: 2
  allowed_symbols: ["_"]
  excluded:
    - iOS_.*

function_parameter_count:
  warning: 6

large_tuple:
  warning: 3
